name: Shell Diff (PR Only)

on:
  pull_request:
    branches: [ '**' ]
    paths:
      - '**/*.sh'
      - '.github/workflows/shell-pr-diff.yml'
  workflow_dispatch: {}

jobs:
  diff-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Differential ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: .
          shellcheck_flags: "-x"
          severity: warning         # 观察期；稳定后可改成 error
